  
- name: Download and install nginx
  yum: name=nginx state=present
  notify: restart nginx
  
- name: 'get CPU cores'
  shell: "cat /proc/cpuinfo| grep processor|wc -l"
  register: cpu


- lineinfile:
    dest: /etc/nginx/nginx.conf
    state: present
    regexp: '^worker_processes'
    line: 'worker_processes {{cpu.stdout}};'